{{/*apiVersion: v1*/}}
{{/*data:*/}}
{{/*  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoid2VrYS5pbyt3ZWthX29jIiwicGFzc3dvcmQiOiJLUlpVUVBHS1ZaRTRJVFlOSDg1R0dWQ0dRVTVNTE0wNlNUQjVQS0k1T1BWUks3RjUzRTdQWDNMVVo1SU44OEk5IiwiZW1haWwiOiJ3ZWthLmlvK3dla2Ffb2NAd2VrYS5pbyIsImF1dGgiOiJkMlZyWVM1cGJ5dDNaV3RoWDI5ak9rdFNXbFZSVUVkTFZscEZORWxVV1U1SU9EVkhSMVpEUjFGVk5VMU1UVEEyVTFSQ05WQkxTVFZQVUZaU1N6ZEdOVE5GTjFCWU0weFZXalZKVGpnNFNUaz0ifX19*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: quay-io*/}}
{{/*  namespace: default*/}}
{{/*type: kubernetes.io/dockerconfigjson*/}}