{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.prefix }}-webhook-certgen"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook-certgen
    app.kubernetes.io/created-by: weka-operator
    app.kubernetes.io/part-of: weka-operator
{{- end }}
