apiVersion: v2
name: weka-operator
description: Weka operator for Kubernetes clusters
type: application
version: "0.0.0"
maintainers:
  - name: weka
    email: support@weka.io
    url: https://weka.io
