apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: client-sample
    app.kubernetes.io/part-of: weka-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: weka-operator
  name: weka-agent
spec:
  version: 4.2.7.1394-5de9249b494cd98dcb943fd71fa9a2fe
  image: quay.io/weka.io/weka-in-container
  imagePullSecretName: quay-cred

  backend:
    netInterface: eth0
    ip:  10.108.32.110
  ioNodeCount: 1
  managementIPs: 10.108.85.130

  agent:
    debug: false

  client:
    debug: false
