apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  namespace: weka-operator-system # should stay the same namespace as the operator, otherwise will also need to duplicate pull secrets
  name: weka-agent
spec:
  version: 4.2.8.327-2e1055ee63d09d7d6cf1ff636db6ed79
  image: quay.io/weka.io/weka-in-container
  imagePullSecretName: quay-cred
  ioNodeCount: 1
  backendIP: 10.108.150.232
  agent:
    debug: false
  client:
    debug: false

  wekaUsername:
    secretKeyRef:
      name: weka-cli
      key: username

  wekaPassword:
    secretKeyRef:
      name: weka-cli
      key: password

