---
apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  namespace: weka-operator-system # should stay the same namespace as the operator, otherwise will also need to duplicate pull secrets
  name: weka-agent
spec:
  version: 4.3.1.20252-d1350f201a919ec3d9dbf78c533e470c
  image: quay.io/weka.io/weka-in-container
  imagePullSecretName: quay-cred

  # Backend nodes are listening on this port
  managementPortBase: 14000

  backendIP: '10.108.196.213'
  agent:
    debug: false
  client:
    debug: false

  wekaUsername:
    secretKeyRef:
      name: weka-cli
      key: username

  wekaPassword:
    secretKeyRef:
      name: weka-cli
      key: password
