---
apiVersion: weka.weka.io/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: weka-operator
    app.kubernetes.io/created-by: weka-operator
  name: cluster-sample
spec:
  size_class: "dev"
  multiplier: 1
