---
apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  namespace: weka-operator-system # should stay the same namespace as the operator, otherwise will also need to duplicate pull secrets
  name: weka-agent
spec:
  version: 4.2.7.64-k8so-beta.6
  image: quay.io/weka.io/weka-in-container
  imagePullSecretName: quay-cred
  #ioNodeCount: 1
  backendIP: 10.108.90.174

  # Backend nodes are listening on this port
  #managementPortBase: 16000

  coreIds:
    - 1
  #backendIP: mbp-k8s-oci-backend-0
  agent:
    debug: false
  client:
    debug: false

  wekaUsername:
    secretKeyRef:
      name: weka-cli
      key: username

  wekaPassword:
    secretKeyRef:
      name: weka-cli
      key: password
