---
apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  namespace: weka-operator-system # should stay the same namespace as the operator, otherwise will also need to duplicate pull secrets
  name: weka-agent
spec:
  version: 4.2.8.1202-23ee44343240776745615486f6ca2a10
  image: quay.io/weka.io/weka-in-container
  imagePullSecretName: quay-cred
  backendIP: 10.0.1.223

  # Backend nodes are listening on this port
  # managementPortBase: 16000

  coreIds:
    - 1
  agent:
    debug: false
  client:
    debug: false

  wekaUsername:
    secretKeyRef:
      name: weka-cli
      key: username

  wekaPassword:
    secretKeyRef:
      name: weka-cli
      key: password
