apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  namespace: weka-operator-system # should stay the same namespace as the operator, otherwise will also need to duplicate pull secrets
  name: weka-agent
spec:
  version: 4.2.7.1394-5de9249b494cd98dcb943fd71fa9a2fe
  image: quay.io/weka.io/weka-in-container
  imagePullSecretName: quay-cred
  ioNodeCount: 1
  backendIP: 10.108.32.110
  agent:
    debug: false
  client:
    debug: false
