apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: client-sample
    app.kubernetes.io/part-of: weka-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: weka-operator
  name: weka-agent
spec:
  version: 4.2.6.3399-9e3798410b34cd34828b641d92c45832
  image: quay.io/weka.io/weka-in-container
  imagePullSecretName: quay-cred
  debug: "1"

  backend:
    netInterface: eth0
    ip: 10.108.217.187
  ioNodeCount: 1
  managementIPs: 10.108.135.54
