apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  namespace: weka-operator-system # should stay the same namespace as the operator, otherwise will also need to duplicate pull secrets
  name: weka-agent
spec:
  version: 4.2.8.312-6a24a384e98df01fb2ab00075d196b81
  image: quay.io/weka.io/weka-in-container
  imagePullSecretName: quay-cred
  ioNodeCount: 1
  backendIP: 10.108.197.248
  agent:
    debug: false
  client:
    debug: false
