apiVersion: weka.weka.io/v1alpha1
kind: Client
metadata:
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: client-sample
    app.kubernetes.io/part-of: weka-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: weka-operator
  name: client-sample
spec:
  # Version of Weka.  I'm assuming that this is a real-enough version for our purposes
  version: 4.3.1