---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: tombstones.weka.weka.io
spec:
  group: weka.weka.io
  names:
    kind: Tombstone
    listKind: TombstoneList
    plural: tombstones
    singular: tombstone
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              container_name:
                type: string
              cr_id:
                type: string
              cr_type:
                type: string
              node_affinity:
                description: "NodeName is a type that holds a api.Node's Name identifier.\nBeing
                  a type captures intent and helps make sure that the node name\nis
                  not confused with similar concepts (the hostname, the cloud provider
                  id,\nthe cloud provider name etc)\n\nTo clarify the various types:\n\n
                  \ - Node.Name is the Name field of the Node in the API.  This should
                  be stored in a NodeName.\n    Unfortunately, because Name is part
                  of ObjectMeta, we can't store it as a NodeName at the API level.\n\n
                  \ - Hostname is the hostname of the local machine (from uname -n).\n
                  \   However, some components allow the user to pass in a --hostname-override
                  flag,\n    which will override this in most places. In the absence
                  of anything more meaningful,\n    kubelet will use Hostname as the
                  Node.Name when it creates the Node.\n\n* The cloudproviders have
                  the own names: GCE has InstanceName, AWS has InstanceId.\n\n\tFor
                  GCE, InstanceName is the Name of an Instance object in the GCE API.
                  \ On GCE, Instance.Name becomes the\n\tHostname, and thus it makes
                  sense also to use it as the Node.Name.  But that is GCE specific,
                  and it is up\n\tto the cloudprovider how to do this mapping.\n\n\tFor
                  AWS, the InstanceID is not yet suitable for use as a Node.Name,
                  so we actually use the\n\tPrivateDnsName for the Node.Name.  And
                  this is _not_ always the same as the hostname: if\n\twe are using
                  a custom DHCP domain it won't be."
                type: string
              persistence_path:
                type: string
            required:
            - cr_id
            - cr_type
            - node_affinity
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
