---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: file-daemon
spec:
  selector:
    matchLabels:
      app: file-daemon
  template:
    metadata:
      labels:
        app: file-daemon
    spec:
      containers:
      - name: file-daemon
        image: ubuntu:latest
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /mnt/root
            name: host-root
        command:
          - sleep
          - '3600'
      volumes:
      - name: host-root
        hostPath:
          path: '/'
 