---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: file-daemon
spec:
  selector:
    matchLabels:
      app: file-daemon
  template:
    metadata:
      labels:
        app: file-daemon
    spec:
      containers:
      - name: file-daemon
        image: docker.io/library/file-daemon:0.0.1