---
# Drivers are archived locally in the {{ root }}/drivers directory
# They are specific to the kernel version of the frontend nodes, but can be
# used with any weka version
# Find the appropriate driver set and upload them to the backend

- name: Upload Drivers
  copy:
    src: "{{ root }}/drivers/{{ item }}-{{ kernel_full_version }}.{{ arch }}.tar.gz"
    dest: /opt/weka/dist/drivers/{{ item }}-{{ weka_version }}-{{ kernel_full_version }}.{{ arch }}.tar.gz
  loop:
    - wekafsgw
    - wekafsio
    - mpin_user
