---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.prefix }}-controller-manager"
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: weka-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: weka-operator
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: {{ if eq .Values.deployController true }} 1 {{else}} 0 {{end}}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      imagePullSecrets:
        - name: "{{ .Values.imagePullSecret }}"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      tolerations:
      {{- if .Values.tolerations }}
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmpdir
          emptyDir: { }
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - command:
            - /weka-operator
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_DEPLOYMENT_IDENTIFIER
              value: "{{ .Values.deploymentIdentifier }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.otelExporterOtlpEndpoint }}"
            - name: VERSION
              value: "{{ .Values.Version }}"
            - name: WEKA_OPERATOR_WEKA_HOME_ENDPOINT
              value: "{{ .Values.wekahome.endpoint }}"
            - name: WEKA_OPERATOR_WEKA_HOME_CACERT_SECRET
              value: "{{ .Values.wekahome.cacertSecret }}"
            - name: WEKA_OPERATOR_WEKA_HOME_INSECURE
              value: "{{ .Values.wekahome.allowInsecureTLS }}"
            - name: WEKA_OPERATOR_WEKA_HOME_ENABLE_STATS
              value: "{{ .Values.wekahome.enableStats }}"
            - name: WEKA_OPERATOR_DEBUG_SLEEP
              value: "{{ .Values.debugSleep }}"
            - name: WEKA_OPERATOR_MAINTENANCE_SA_NAME
              value: "{{ .Values.prefix }}-maintenance"
            - name: WEKA_MAINTENANCE_IMAGE
              value: "{{ .Values.maintenanceImage | default "busybox" }}"
            - name: WEKA_MAINTENANCE_IMAGE_PULL_SECRET
              value: "{{ .Values.maintenanceImagePullSecret | default "" }}"
            - name: WEKA_OCP_PULL_SECRET
              value: "{{ .Values.ocpCompatibility.driverToolkitSecretName }}"
            - name: WEKA_OCP_TOOLKIT_IMAGE_BASE_URL
              value: "{{ .Values.ocpCompatibility.driverToolkitImageBaseUrl }}"
            - name: WEKA_COS_ALLOW_DISABLE_DRIVER_SIGNING
              value: "{{ .Values.gkeCompatibility.disableDriverSigning }}"
            - name: WEKA_COS_ALLOW_HUGEPAGE_CONFIG
              value: "{{ .Values.gkeCompatibility.hugepageConfiguration.enabled}}"
            - name: WEKA_COS_GLOBAL_HUGEPAGE_SIZE
              value: "{{ .Values.gkeCompatibility.hugepageConfiguration.hugepageSize }}"
            - name: WEKA_COS_GLOBAL_HUGEPAGE_COUNT
              value: "{{ .Values.gkeCompatibility.hugepageConfiguration.hugepageCount }}"
            - name: WEKA_COS_SERVICE_ACCOUNT_SECRET
              value: "{{ .Values.gkeCompatibility.gkeServiceAccountSecret }}"
            - name: LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: LOG_TIME_ONLY
              value: "{{ .Values.logging.timeOnly }}"
            - name: HEALTH_PROBE_BIND_ADDRESS
              value: "{{ .Values.healthProbeBindAddress }}"
            - name: OPERATOR_METRICS_BIND_ADDRESS
              value: "{{ .Values.operatorMetricsBindAddress }}"
            - name: ENABLE_LEADER_ELECTION
              value: "{{ .Values.enableLeaderElection }}"
            - name: ENABLE_CLUSTER_API
              value: "{{ .Values.enableClusterApi }}"
            - name: ENABLE_TOMBSTONE_GC
              value: "{{ .Values.persistence.containerTombstone.gc.enabled }}"
            - name: TOMBSTONE_GC_INTERVAL
              value: "{{ .Values.persistence.containerTombstone.gc.interval }}"
            - name: TOMBSTONE_EXPIRATION
              value: "{{ .Values.persistence.containerTombstone.gc.retention }}"
            - name: RECONCILE_TIMEOUT
              value: "{{ .Values.reconcileTimeout }}"
            - name: KUBE_EXEC_TIMEOUT
              value: "{{ .Values.kubeExecTimeout }}"
            - name: WEKA_ALLOC_ZOMBIE_DELETE_AFTER
              value: "{{ .Values.wekaAllocZombieDeleteAfter }}"
            {{- if .Values.persistence.containerTombstone.gc.allowDeleteOnNodeMissing }}
            - name: ALLOW_TOMBSTONE_DELETE_ON_NODE_MISSING
              value: "true"
            {{- end }}
            - name: MAX_WORKERS_WEKACLUSTER
              value: "{{ .Values.maxWorkers.wekaCluster }}"
            - name: MAX_WORKERS_WEKACONTAINER
              value: "{{ .Values.maxWorkers.wekaContainer }}"
            - name: MAX_WORKERS_WEKACLIENT
              value: "{{ .Values.maxWorkers.wekaClient }}"
            - name: MAX_WORKERS_WEKAMANUALOPERATION
              value: "{{ .Values.maxWorkers.wekaManualOperation }}"
            - name: MAX_WORKERS_WEKAPOLICY
              value: "{{ .Values.maxWorkers.wekaPolicy }}"
            - name: MAX_WORKERS_TOMBSTONE
              value: "{{ .Values.maxWorkers.tombstone }}"
            - name: METRICS_CLUSTERS_ENABLED
              value: "{{ .Values.metrics.clusters.enabled }}"
            - name: METRICS_CONTAINERS_ENABLED
              value: "{{ .Values.metrics.containers.enabled }}"


          image: "{{ .Values.image.repository }}:{{if not (empty .Values.image.tag)}}{{ .Values.image.tag }}{{else}}{{ .Chart.Version }}{{end}}"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp
              name: tmpdir
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            {{- toYaml .Values.manager.resources | nindent 12 }}
      serviceAccountName: "{{ .Values.prefix }}-controller-manager"
      terminationGracePeriodSeconds: 10
