---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-node-labeller
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch", "get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: labeller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-node-labeller
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.prefix }}-controller-manager"
    namespace: "{{ .Values.prefix }}-system"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weka-labeller
  labels:
    app.kubernetes.io/name: weka-labeller
    app.kubernetes.io/part-of: weka-operator
    app.kubernetes.io/created-by: weka-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: weka-labeller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weka-labeller
    spec:
      serviceAccountName: "{{ .Values.prefix }}-controller-manager"
      imagePullSecrets:
        - name: "{{ .Values.imagePullSecret }}"
      containers:
        - image: "quay.io/weka.io/weka-operator-node-labeller:{{ .Values.image.tag }}"
          name: weka-labeller
          imagePullPolicy: Always
          command: ["./node-labeller"]
          args:
            - "--logtostderr"
            - "--v=2"
          securityContext:
            privileged: true #Needed for /dev
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: sys
              mountPath: /sys
            - name: dev
              mountPath: /dev
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
