"apiVersion": "v1"
"data":
  "416.94.202406172220-0": "dde3cd6a75d865a476aa7e1cab6fa8d97742401e87e0d514f3042c3a881e301f"
  "416.94.202406251923-0": "8ef92caba7bd5d6ab3a139da782bf5651c2a40802eaa33b0c7899a7e897e007b"
  "416.94.202407030122-0": "e5e6de7572003ac560f113a0082594a585c49d51801f028f699b15262eff7c02"
  "416.94.202407081958-0": "a73204d0c03454b02656801ca4c49cb2d8b0d54645bb90f74622df335c82dce1"
  "416.94.202407171205-0": "5ad87db06c4c2fe73ae1e369f0bc3c920f0f30f8c6bffb330d85c6b383dfc531"
  "416.94.202407231922-0": "b6888f97ae95a3fad643c7d1da50ca258309ad8e58082da2304a259392b7fd42"
  "416.94.202407251849-0": "d00bda2d25cbe078e1260fbe7257dc135a0a93b876025c041c0d937141bd806d"
  "416.94.202408062045-0": "af687f54b6a0cbf28490b0c7e68d164c0f86492c8c9b2ccb45e416d1751e1dd2"
  "416.94.202408132101-0": "08c72da1a2939f2123d03d84d23dd63180eac09fcc7a8fb9aa6c02f2daf5300a"
  "416.94.202408200132-0": "83b5bb8d778c7128113058e3a533e2b35a777bcce2058277367081a9fe610e35"
  "416.94.202408260940-0": "66d1fdd2b231a474a434a3aa603fed39137485c8f5b51d84fdd712f4b225638c"
  "416.94.202409040013-0": "8bdd6c5f1a7e184af2eb1a30363035ffde1642b3800d824de2dcc949048f07a8"
  "416.94.202409092052-0": "da79a292c75b71152f7693ce63de586f1d083ccc2d271913b6f64bb4deadf4d2"
  "416.94.202409181502-0": "78828089c880e1c7187e0e61948628721a5d686fc0f13e9804e60897c78594dd"
  "416.94.202409191851-0": "3cc13f2a17a3fd127c1d91fb13cf785872d981555ca2a5f7ce1dd552438e5cb3"
  "416.94.202410020522-0": "5cf5d4a15f410aa6bb74d05715cf4eb5630478b6271554f30a8a716dfdfe5bcc"
  "417.94.202409121747-0": "5ade3bb39301509ce941b053f2c943e381b8ea5f6d5337c72a58ee33ff27b391"
"kind": "ConfigMap"
"metadata":
  "name": "ocp-driver-toolkit-images"