---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weka-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - weka.weka.io
  resources:
  - driveclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weka.weka.io
  resources:
  - driveclaims/finalizers
  verbs:
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - driveclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - tombstones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weka.weka.io
  resources:
  - tombstones/finalizers
  verbs:
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - tombstones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekaclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weka.weka.io
  resources:
  - wekaclients/finalizers
  verbs:
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekaclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekaclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weka.weka.io
  resources:
  - wekaclusters/finalizers
  verbs:
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekaclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekacontainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weka.weka.io
  resources:
  - wekacontainers/finalizers
  verbs:
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekacontainers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekamanualoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weka.weka.io
  resources:
  - wekamanualoperations/finalizers
  verbs:
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekamanualoperations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekapolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weka.weka.io
  resources:
  - wekapolicies/finalizers
  verbs:
  - update
- apiGroups:
  - weka.weka.io
  resources:
  - wekapolicies/status
  verbs:
  - get
  - patch
  - update
