---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.imagePullSecret.name }}"
  labels:
    app: weka-operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: '{{ template "weka-operator.dockerconfigjson" . }}'
