{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.prefix }}-webhook-service"
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: weka-operator
    app.kubernetes.io/part-of: weka-operator
spec:
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
      name: https
  selector:
    control-plane: controller-manager
{{- end }}
