apiVersion: v1
kind: ConfigMap
metadata:
  name: weka-boot-scripts
  namespace: {{ .Release.Namespace }}
data:
  start-weka-agent.sh: |
{{ .Files.Get "resources/start-weka-agent.sh" | indent 4 }}
  start-weka-container.sh: |
{{ .Files.Get "resources/start-weka-container.sh" | indent 4 }}
  supervisord.conf: |
{{ .Files.Get "resources/supervisord.conf" | indent 4 }}
  syslog-ng.conf: |
{{ .Files.Get "resources/syslog-ng.conf" | indent 4 }}
  start-syslog-ng.sh: |
{{ .Files.Get "resources/start-syslog-ng.sh" | indent 4 }}
