---
name: Build
on:
  push:

jobs:
  optimize_ci:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Optimize CI
        id: check_skip
        uses: withgraphite/graphite-ci-action@main
        with:
          graphite_token: ${{ secrets.GRAPHITE_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: optimize_ci
    if: needs.optimize_ci.outputs.skip == 'false'
    env:
      GOPRIVATE: github.com/weka

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up SSH # See: https://github.com/webfactory/ssh-agent?tab=readme-ov-file#support-for-github-deploy-keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.OPERATOR_DEPLOY_SSH_KEY }}
            ${{ secrets.WEKA_K8S_API_DEPLOY_SSH_KEY }}
            ${{ secrets.GO_WEKA_OBSERVABILITY_DEPLOY_SSH_KEY }}
            ${{ secrets.GO_STEPS_ENGINE_DEPLOY_SSH_KEY }}
      - name: Setup access for private go modules
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/
      - name: Install submodules
        run: git submodule update --init --recursive

      - name: Setup Go (supports caching)
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup go
        run: |
          go version
          go mod download

      - name: Setup envtest
        run: |
          make envtest
          ./bin/setup-envtest use --bin-dir ./bin 1.26.0

      - name: Test
        run: |
          go generate ./...
          make generate
          make test

#      - uses: goreleaser/goreleaser-action@v5
#        id: goreleaser
#        with:
#          distribution: goreleaser
#          version: latest
#          args: release --snapshot --clean
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build chart
#        run: |
#          echo '${{ steps.goreleaser.outputs.metadata }}' | jq '.version'
#          export VERSION=$(echo '${{ steps.goreleaser.outputs.metadata }}' | jq '.version')
#          make chart VERSION="${VERSION}"
