---
name: Package Operator (HELM)
run-name: ${{ github.actor }} is building the Helm package

# make sure only one workflow is running at a time
concurrency:
  group: package-operator
  cancel-in-progress: false

on:
  push:
    branches:
      - main
      - release/*

  workflow_dispatch:
    inputs:
      version-name:
        description: 'Name of the version to be released'
        required: true

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write
  discussions: write
  checks: write


jobs:
  optimize_ci:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Optimize CI
        id: check_skip
        uses: withgraphite/graphite-ci-action@v0.0.9
        with:
          graphite_token: ${{ secrets.GRAPHITE_TOKEN }}

  Helm-Release:
    runs-on: ubuntu-latest
    needs: optimize_ci
    if: needs.optimize_ci.outputs.skip == 'false'
    env:
      GOPRIVATE: github.com/weka
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.SCALAR_WORKERS_APP_ID }}
          private-key: ${{ secrets.SCALAR_WORKERS_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Setup access for private go modules
        run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf https://github.com/
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf git@github.com:
          echo "machine github.com login x-access-token password ${{ steps.app-token.outputs.token }}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      # See: https://github.com/webfactory/ssh-agent?tab=readme-ov-file#using-multiple-deploy-keys-inside-docker-builds
      - name: Collect Git files in a directory that is part of the Docker build context
        run: |
          mkdir -p dockerfile_files
          cp -r ~/.gitconfig ~/.netrc dockerfile_files/
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"
          cache: true
          cache-dependency-path: |
            go.sum
            pkg/weka-k8s-api/go.sum
            pkg/go-steps-engine/go.sum
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'npm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QuayUsername }}
          password: ${{ secrets.QuayPassword }}
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.3
      - name: Login to Registry
        run: helm registry login quay.io/weka.io --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }}
      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install dependencies
        if: github.event_name != 'workflow_dispatch'
        run: npm install
      - name: Generating version
        if: github.event_name != 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release -- --dry-run
      - name: Read VERSION from inputs
        id: version_input
        if: github.event_name == 'workflow_dispatch'
        run: echo "VERSION=${{ github.event.inputs.version-name }}" >> $GITHUB_ENV
      - name: Read VERSION file
        id: version
        if: github.event_name != 'workflow_dispatch'
        run: echo "VERSION=$(cat .VERSION)" >> $GITHUB_ENV
      - name: build version
        if: ${{ env.VERSION != '' }}
        run: VERSION=${{ env.VERSION }} ./build-release.sh
      - name: Create release
        if: ${{ env.VERSION != '' && github.event_name != 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
      - name: Add operator version as artifact
        if: ${{ env.VERSION != '' }}
        run: echo "${{ env.VERSION }}" > operator-version.txt
      - name: Upload artifact
        if: ${{ env.VERSION != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: operator-version
          path: operator-version.txt
          retention-days: 1
