---
name: Package Operator (HELM)
run-name: ${{ github.actor }} is building the Helm package
on:
  push:
    branches:
      - main
      - release/*

permissions:
  contents: write

jobs:
  Helm-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/iron'
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
      - name: Docker login
        run: docker login --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }} quay.io
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
      - name: Login to Registry
        run: helm registry login quay.io/weka.io --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }}
      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install dependencies
        run: npm install
      - name: Generating version
        run: npm run release -- --dry-run
      - name: Read VERSION file
        id: version
        run: echo "VERSION=$(cat .VERSION)" >> $GITHUB_ENV
      - name: build version
        run: VERSION=${{ env.VERSION }} ./build-release.sh
      - name: Create release
        run: npm run release
