---
name: Package Operator (HELM)
run-name: ${{ github.actor }} is building the Helm package
on:
  push:
    branches:
      - main
      - fix-release
permissions:
  contents: write

jobs:
  Helm-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - run: go version

      - name: Docker login
        run: docker login --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }} quay.io

      - name: Building Release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          hooks: goreleaser
          update-file: charts/weka-operator/Chart.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Chart
        if: steps.semrel.outputs.version != ''
        run: |
          echo '${{ steps.semrel.outputs.version }}'
          make chart VERSION=${{ steps.semrel.outputs.version }}
      - name: Configure git
        if: steps.semrel.outputs.version != ''
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        if: steps.semrel.outputs.version != ''
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
      - name: Login to Registry
        if: steps.semrel.outputs.version != ''
        run: helm registry login quay.io/weka.io --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }}
      - name: Push chart to registry
        if: steps.semrel.outputs.version != ''
        run: helm push charts/weka-operator-*.tgz oci://quay.io/weka.io/helm
