---
name: Package Operator (HELM)
run-name: ${{ github.actor }} is building the Helm package
on:
  push:
    branches:
      - release/v0
      - release/v1-beta

permissions:
  contents: write

jobs:
  Helm-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
      - run: go version

      - name: Docker login
        run: docker login --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }} quay.io

      - name: Building Release
        run: |
          npm install -g go-semantic-release
          go-semantic-release --version
          go-semantic-release --token ${{ secrets.GITHUB_TOKEN }} \
            --provider-opt slug=weka/weka-operator \
            --hooks goreleaser \
            --version-file \
            --match $(jq -r '.match' < .semrelrc )
          echo "version=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Build Chart
        if: steps.semrel.outputs.version != ''
        run: |
          echo 'v${{ steps.semrel.outputs.version }}'
          make chart VERSION=v${{ steps.semrel.outputs.version }}
      - name: Configure git
        if: steps.semrel.outputs.version != ''
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        if: steps.semrel.outputs.version != ''
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
      - name: Login to Registry
        if: steps.semrel.outputs.version != ''
        run: helm registry login quay.io/weka.io --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }}
      - name: Push chart to registry
        if: steps.semrel.outputs.version != ''
        run: helm push charts/weka-operator-*.tgz oci://quay.io/weka.io/helm
