---
name: Package Operator (HELM)
run-name: ${{ github.actor }} is building the Helm package
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Helm-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - run: go version

      - name: Install kustomize
        run: make kustomize

      - name: Setup Kind
        uses: helm/kind-action@v1.8.0

      - name: Build Chart
        run: |
          make templates
          make docker-buildx

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Login to Registry
        run: helm registry login quay.io/weka.io --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }}
