---
name: Package Operator (HELM)
run-name: ${{ github.actor }} is building the Helm package

# make sure only one workflow is running at a time
concurrency:
  group: package-operator
  cancel-in-progress: false

on:
  push:
    branches:
      - main
      - release/*

  workflow_dispatch:
    inputs:
      version-name:
        description: 'Name of the version to be released'
        required: true

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write
  discussions: write
  checks: write


jobs:
  optimize_ci:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Optimize CI
        id: check_skip
        uses: withgraphite/graphite-ci-action@main
        with:
          graphite_token: ${{ secrets.GRAPHITE_TOKEN }}

  Helm-Release:
    runs-on: ubuntu-latest
    needs: optimize_ci
    if: needs.optimize_ci.outputs.skip == 'false'
    env:
      GOPRIVATE: github.com/weka
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up SSH  # See: https://github.com/webfactory/ssh-agent?tab=readme-ov-file#support-for-github-deploy-keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.OPERATOR_DEPLOY_SSH_KEY }}
            ${{ secrets.WEKA_K8S_API_DEPLOY_SSH_KEY }}
            ${{ secrets.GO_WEKA_OBSERVABILITY_DEPLOY_SSH_KEY }}
      - name: Setup access for private go modules
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/
      # See: https://github.com/webfactory/ssh-agent?tab=readme-ov-file#using-multiple-deploy-keys-inside-docker-builds
      - name: Collect Git and SSH config files in a directory that is part of the Docker build context
        run: |
          mkdir -p dockerfile_files
          cp -r ~/.gitconfig ~/.ssh dockerfile_files/
          sed 's|/home/runner|/root|g' -i.bak dockerfile_files/.ssh/config
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.local/share/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"
      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/iron'
      - name: Docker login
        run: docker login --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }} quay.io
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
      - name: Login to Registry
        run: helm registry login quay.io/weka.io --username ${{ secrets.QuayUsername }} --password ${{ secrets.QuayPassword }}
      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install dependencies
        if: github.event_name != 'workflow_dispatch'
        run: npm install
      - name: Generating version
        if: github.event_name != 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release -- --dry-run
      - name: Read VERSION from inputs
        id: version_input
        if: github.event_name == 'workflow_dispatch'
        run: echo "VERSION=${{ github.event.inputs.version-name }}" >> $GITHUB_ENV
      - name: Read VERSION file
        id: version
        if: github.event_name != 'workflow_dispatch'
        run: echo "VERSION=$(cat .VERSION)" >> $GITHUB_ENV
      - name: build version
        if: ${{ env.VERSION != '' }}
        run: VERSION=${{ env.VERSION }} ./build-release.sh
      - name: Create release
        if: ${{ env.VERSION != '' && github.event_name != 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
      - name: Add operator version as artifact
        run: echo "${{ env.VERSION }}" > operator-version.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: operator-version
          path: operator-version.txt
