---
name: Release
run-name: Release - ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - "pre-release/**"

permissions:
  contents: write

jobs:
  call-setup:
    uses: ./.github/workflows/setup.yaml

  semantic-release:
    runs-on: ubuntu-latest
    needs: call-setup

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          pwd
          ls .
          ls pyproject.toml
          ls poetry.lock

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Set Channel ID
        run: |
          echo "CHANNEL=$(git branch --show-current)" >> $GITHUB_ENV

      - name: Calculate version
        run: |
          echo "VERSION=$(poetry run semantic-release version --print --build-metadata ${CHANNEL})" >> $GITHUB_ENV
          echo "TAG=$(poetry run semantic-release version --print-tag --build-metadata ${CHANNEL})" >> $GITHUB_ENV

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_metadata: ${{ env.CHANNEL }}
